### ISSUE TITLE
Allow bridge and FRAME applications to live on different parachains

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/snowbridge#173]
The goal is to allow the bridge module to interact with ETH and ERC20 applications living on separate parachains. Messaging will be implemented using XCMP.

The interaction should be bidirectional:

* Minting eth: Bridge sends message to ETH App
* Burning eth: EthApp sends message to Bridge

We'll need to come up with a design for this, and think carefully about issues of security and trust.

Some of the issues we'll need to implement to make this possible:

- [ ] Add public dispatchables to bridge and FRAME applications
- [ ] Allow dynamic registration of FRAME applications with the bridge

**Comment by rakanalh** [comment]
Following a call the Efinity team had with @musnit and @vgeddes, @fmiguelgarcia and I have considered how to implement message forwarding to snowbridge and resolve this issue.

## Message Forwarding

Message forwarding is leveraging XCM so that snowbridge is able to forward calls emitted by contracts to a the 3rd-party parachain that is interested in handling these calls.

To enable message forwarding on Snowbridge, one of the following 3 approaches has to be implemented:

1. ERC20 → Parachain Mapping (1 to 1)
2. Parachain specific contracts
3. Parachain ID as parameter
 
### Solution 1: ERC20 → Parachain Mapping

In this solution, a pallet is added to snowbridge where the ERC20 token is registered along with the parachain ID that handles this ERC20 token. This means that calls dispatched into the bridge will need to be routed to the designated parachain depending on this mapping.

**Pros:**
- Easy to implement

**Cons:**
- Mapping restricts multiple apps from leveraging the bridge to operate the token. Example: multiple parachain who want to operate on USDT.
- Implicit Mapping, meaning that the user has to rely on the fact that the mapping that the bridge has will lead to the token landing on the correct parachain. 

### Solution 2: Parachain specific contracts

In this solution:

- Each parachain has it’s own ERC20App, ERC721, NFT, DOTApp contracts deployed.
- These contracts need to include their own addresses in the events emitted.
- Relayer submits the call to the bridge parachain along with the originating address of the read event.
- A pallet is introduced in the bridge parachain to map these contract addresses to the parachain that handles events emitted from these contract.

**Pros:**
- Isolate parachain specific contracts from other parachains.
- Supports the use case for multiple parachains being able to handle the same token.

**Cons:**
- Contracts deployment is left to the parachain maintainers while not leveraging contracts deployed by the bridge itself.
- Implicit Mapping, meaning that the user has to rely on the fact that the mapping that the bridge has will lead to the token landing on the correct parachain.
- Relayer has to support dynamic registration of contracts bundle for each parachain to watch events coming out.

### Solution 3: Parachain ID as parameter

In this solution:

- ERC20App, ERC721App, ETHApp contracts should be modified to accept Parachain ID to which the transfer will be relayed. A Parachain ID of 0 could mean the transfer is meant for the bridge itself.
- The relayer detects events and submits messages from/to Inbound / Outbound channels. 
   - For Ethereum, processing inbound messages means submitting transactions to the said contracts. 
   - For Snowbridge’s parachain, the messages are registered  into the Inbound channel and those messages are dispatched by the dispatcher pallet into the final targeted pallet to process the call. 
   - Only in Eth → Parachain case, the bridge extracts the parachain ID from the call’s payload and sends an XCM message to the targeted parachain.

**Pros:**
- Explicit target parachain
- No mapping required
- No additional contract deployments required

**Cons:**
- User has to be aware of the parachain ID when an eth transaction to lock is submitted.

We are leaning towards solution 3 since it:
1. Requires minimal modifications
2. Leverages the most out of existing infrastructure that is going to be offered by snowbridge.

Please let us know your thoughts on the above so that we can collaborate on the implementation.

**Comment by vgeddes** [comment]
@rakanalh Work on our low-level channels API is progressing well, with most of the ethereum -> polkadot flow implemented. I'm expecting to release the feature for beta testing in early to mid December.

Working branch:
https://github.com/Snowfork/snowbridge/compare/vincent/channels-api

I'll be cutting a draft PR soon for some interim review.

**Comment by vgeddes** [comment]
obsolete. we are adapting our bridge for XCMv3 which handles this problem. Tracked in Linear
