### ISSUE TITLE
Potentially redundant gas checking in InboundChannel

### ISSUE THREAD

**Issue by denalimarsh** [Snowfork/snowbridge#268]
Test if gas checking in `InboundChannel.sol`, `IncentivizedInboundChannel.sol` is redunant and if so remove it.

Do we even need those gas checks? When we execute the calls, we limit the gas, which might be enough?

_Originally posted by @philipstanislaus in https://github.com/Snowfork/polkadot-ethereum/pull/266#discussion_r573777242_

**Comment by vgeddes** [comment]
Agree, I bumped into issues around this while testing the new DOT app (which seems to be gas-heavy until I optimize it further), and had to comment out the gas checks in the solidity code.

I also changed the relayer to use a static gas limit when making calls, instead of using `estimateGas` as that caused ganache to crash.

Anyway will submit a PR for this.

**Comment by vgeddes** [comment]
The gas checks in Solidity also have the potential to break the bridge by refusing messages, even though they were accepted for delivery by the Substrate side. The refusals would lead to mismatched nonces and effectively prevent further messages being sent over the bridge.

**Comment by musnit** [comment]
@vgeddes No, our gas checking logic nd constants should be high enough to ensure that all messages in a commitment will be accepted. It should not refuse messages. Do you have an example of your concern?

**Comment by vgeddes** [comment]
We have a linear issue for this: https://linear.app/snowfork/issue/SNO-89/channel-flow-control-limits
