### ISSUE TITLE
submitInitial in BeefyClient should have the commitment as a parameter

### ISSUE THREAD

**Issue by awesie** [Snowfork/snowbridge#784]
Currently, `submitInitial` and `submitInitialWithHandover` take the commitment hash as a parameter instead of the actual commitment [1]. This is insecure because you cannot submit an equivocation proof with only the hash, you need the commitment as well [2]. As such, an attacker would not be punishable.

[1] https://github.com/Snowfork/snowbridge/blob/main/core/packages/contracts/contracts/BeefyClient.sol#L184
[2] https://github.com/paritytech/substrate/blob/master/primitives/consensus/beefy/src/lib.rs#L232

**Comment by vgeddes** [comment]
Hi @awesie,

So `submitInitial` is only the first phase of submission. It must also paired up with subsequent call to `submitFinal`, in which the full commitment must be supplied. So if we chose to support equivocation proofs, the capability is there.

Currently our BEEFY client isn't designed to support equivocation proofs and reports, simply because there is no protocol to report the equivocation to the relay chain. The equivocation checking in BEEFY protocol is purely for "online" equivocations in which both commitments are gossiped around the network.

Assuming we mandate that relayers put up collateral, we could use equivocation proofs to slash the relayer submitting fraudulent commitments. However that collateral would need to match the value locked into the bridge, which makes it not a practical solution.

**Comment by vgeddes** [comment]
Beefy now supports reporting equivocations, so we've implemented this change in `main`.
